#!/usr/bin/env python
# vim: set encoding=utf-8 et sw=4 sts=4 :

from threader import threaderdaemon
import sys, os

import logging 
log = logging.getLogger('threaderd')

try:
    start_threads = int(sys.argv[1])
except:
    start_threads = 5

logging.basicConfig(                                              
    level   = logging.DEBUG,
    format  = '%(asctime)s - %(levelname)-8s - %(name)-10s - %(message)s',
    datefmt = '%H:%M:%S',
    )
try:
    t = threaderdaemon.ThreaderDaemon()
    t.run(start_threads)
except Exception, e:
    log.error(str(e))
