#!/usr/bin/env python
# vim: set encoding=utf-8 et sw=4 sts=4 :

import sys, os
from threader import threaderdaemon

import logging 
log = logging.getLogger('threaderd')

try:
    processor = sys.argv[1]
    start_threads = int(sys.argv[2])
except:
    processor = 'Processor2'
    start_threads = 5

logging.basicConfig(                                              
    level   = logging.DEBUG,
    format  = '%(asctime)s - %(levelname)-8s - %(name)-10s - %(message)s',
    datefmt = '%H:%M:%S',
    )
try:
    t = threaderdaemon.ThreaderDaemon()
    t.run(processor=processor, qty=start_threads)
except Exception, e:
    log.error(str(e))
